### ISSUE TITLE
Cookie compliance module for Odd Drupal 

### ISSUE THREAD

**Issue by marcusmansson** [oddhill/odddrupal#19]
Since it's required by law to inform website visitors of cookie usage on web sites, wouldn't it be wise to have a default cookie disclaimer module built into odd drupal? 

For instance: https://www.drupal.org/project/simple_cookie_compliance

**Comment by olofbokedal** [comment]
It'd be a good idea to include this in Odd Drupal if we want it for every site. And I know it's the law, but.... It's so god damn annoying!

I'd say that if Odd Hill decides that we should enforce this disclaimer on every site that we build, sure, then it's time. But it'll stay out of Odd Drupal until then.

Perhaps raise an issue on a tactical meeting for the production circle? To get input from other people etc and perhaps investigate the possibility.

**Comment by olofbokedal** [comment]
Closing this since we need an overall strategy for how we should handle this law.
