### ISSUE TITLE
Downgrade views until ajax is fixed

### ISSUE THREAD

**Issue by madshoffnielsen** [oddhill/odddrupal#3]
Views 3.10 breaks ajax in filter use views 3.8 until its fixed

**Comment by jenslind** [comment]
Link to issue on Drupal.org or steps to reproduce would be nice.

**Comment by madshoffnielsen** [comment]
Happens when you use exposed filter in combination with ajax loading then ajax stops working and creates page load instead of loading in background with ajax.

https://www.drupal.org/node/2425099

**Comment by olofbokedal** [comment]
Why was this closed?

**Comment by madshoffnielsen** [comment]
Views upgraded to 7.x-3.13 should solve the problem.
