### ISSUE TITLE
Disable XHProf output and debug stats at the bottom of the page

### ISSUE THREAD

**Issue by NormySan** [oddhill/odddrupal#30]
The reasoning for this is because it outputs when using console commands, it destroys the intended layout of the page and is just very annoying. This could be a opt-in setting that you yourself have to enable if you've got performance issues that needs to be fixed.

**Comment by olofbokedal** [comment]
Agreed. I thought that it'd be a good help in every project, but that turned out wrong.

I think we should remove xhprof module completely, so it'll be up to every developer to install it when needed. Keep the bloat away!
